api/tls_context.proto

This makes more sense, from the TLS handshake point of view.

TLS: move TlsParameters to the first field.

---

api/address.proto
api/lds.proto

As discussed offline and in https://github.com/lyft/envoy-api/issues/14.

lds: empty address implies bind 0.0.0.0/::.

---

LICENSE

Copied from lyft/envoy.git. We will need this to import back into
Google.

Add Apache 2.0 LICENSE file.

---

api/address.proto
api/cds.proto
api/eds.proto
api/lds.proto

This will be useful for Google and other site specific extension of the
resolving of both names and ports. For listeners, ports and bound
addresses can be expressed in a site-specific format. For upstreams,
host names can be resolved using the plugin.

lds: support resolver extensibility.

---

api/cds.proto
api/health_check.proto
api/lds.proto
api/rds.proto
api/tls_context.proto

As previously pointed out in #9, the empty string is not generally a useful
value in the xDS APIs, so can be be considered equivalent to an unset
field. This is now documented in principles in #28 as well.

Replace google.protobuf.StringValue with string.

---

api/base.proto
api/cds.proto
api/eds.proto
api/hds.proto
api/health_check.proto

This provides some free conversion routines in the various language
proto bindings, e.g. conversion from Python datetime.timedelta.

Replace custom Duration with google.protobuf.Duration well known type.

---

api/tls_context.proto

SPKI doesn't change when certificate is reissued, so it works better
with short-lived certificates.
This is also the same format as used in HTTP Public Key Pinning.

TLS: add ability to hash SPKI instead of certificate.

---

api/base.proto
api/filter/BUILD
api/filter/http_connection_manager.proto
api/rds.proto

This is the first example of a network filter proto. Later patches will supply code to convert to google.protobuf.Struct and merge with LDS protos.

filter: http_connection_manager proto.

---

api/eds.proto

Renamed LocalityEndpoints message in eds.proto, as it was clashing with a message with the same name in hds.proto.

Renamed LocalityEndpoints message in eds.proto

---

examples/service_envoy/listeners.pb
tools/BUILD
tools/generate_listeners.py

This tools will take a LDS response message with holes where opaque
filter configs should go, and fill them with the Struct equivalent of
the protos supplied for the filter configs. It emits both output
text proto and JSON.
To generate example output listeners.pb and listeners.json, run bazel
build //examples/service_envoy:listeners_files.

tools: generate_listeners.

---

api/base.proto
api/filter/http_connection_manager.proto
api/lds.proto
api/rds.proto

There are multiple uses for opaque metadata that is associated with the
specific listener/filter chain/route that a request matches on:
1. Logging. Similar to header values, we can log the metadata values.
A listener might belong to a higher level concept in the
configuration language that generated LDS protos, e.g. there might be
a rule identifier expressed. This metadata allows logs to reflect the
rule identifier.
2. Future custom stats backends might use metadata to guide where and
how stats are emitted. E.g. the metadata might include information
about which stats collector to emit to.
3. Proprietary filters can receive additional inputs via the metadata.
The per-filter metadata generalizes and replaces the opaque_config in
RDS ForwardAction.
The metadata is structured such that each …

lds/rds: add opaque per-filter metadata.

---

api/rds.proto

This was a clarification suggested by @amb67, since traffic mirroring is a well known term but shadowing less so.

rds: rename shadowing to request mirroring.

---

api/filter/BUILD
api/filter/mongo_proxy.proto
api/filter/rate_limit.proto
api/filter/tcp_proxy.proto

TCP proxy filter now has an idle timeout and the source match (and rest
of route match as well) are now in the FilterChainMatch in
https://github.com/lyft/envoy-api/pull/49.
Fixes #23, #45.

api/filter: add tcp_proxy/rate_limit/mongo_proxy filter config protos.

---

api/lds.proto

* Allow multiple CIDR ranges to be provided for the prefix match. This
is useful when you have the same listener config in multiple subnets,
each subnet with the same suffix allocation of VIPs and the CIDR prefix
assigned by region/zone, e.g. when using the GCP subnetworks feature.
E.g. the service is on 0.0.0.37 in subnetworks 10.1.0.0 in US and
10.2.0.0 in Asia.
* Add source IP/port matching similar to existing TCP proxy filter. This
moves the route configuration from the TCP proxy filter to the
FilterChainMatch, making it also available to HTTP connections.
Fixes #6 and #36.

lds: prefix ranges and source IP/port matching.

---

api/base.proto
api/cds.proto
api/rds.proto

While still supporting only 2 priorities today, this PR leaves room for
an additional finite number of priorities via enum extension. Since
we're not planning on reflecting arbitrary downstream priorities in the
upstream connection, we only expect a small number of priorities to be
useful in configuring routes and clusters.
Fixes #1.

rds/cds: allow future extension of upstream priorities.

---

bazel/repositories.bzl

The source files needed for descriptor generation, at https://github.com/lizan/envoy/blob/aa3aada1fa9e2557e34c1144d91bb2241da84ebf/test/proto/BUILD#L24 in lyft/envoy#1079

Export protobuf sources as filegroup

---

api/base.proto
api/cds.proto
api/eds.proto
api/lds.proto
api/rds.proto

This PR allows for easier implementation of a unified subscription model
in Envoy for gRPC/REST/inotify filesystem config updates:
* The DiscoveryRequest basically looks the same in all subscription APIs
today, so factored out to DiscoveryRequest.
* xDiscoveryResponse now uses a consistent convention. This will allow
C++ template level duck typing to populate the response in a single
implementation for all APIs. This is mostly relevant for the filesystem
watch implementation, where we need to map from resource names to file
paths, but could also make API server implementation easier
potentially.

api: factor out discovery request/response commonalities.

---

api/base.proto
api/cds.proto
api/eds.proto
api/lds.proto
api/rds.proto

* Factor all subscription responses to DiscoveryResponse message with an Any
resource type. This further simplifies the Subscription interface in
the Envoy client, as it no longer needs to be templatized on the
response type.
* Replace version_info bytes type with string. This allows plain
strings to be used in JSON representations rather than base64 encoded
strings as required in the canonical proto3 translation of bytes.
* Clarify ACK/NACK semantics with version_info in comments.
Fixes #85.

api: generalize DiscoveryResponse and some versioning updates.

---

api/filter/http_connection_manager.proto

When doing logging to RPC endpoints in proto format we need to know two
config details:
1) The RPC endpoint.  This is a string like the path, but rather than
semantic overloading make this explicit.
2) Custom headers to include.  We'll populate all of the names fields in
the AccessLog proto but users can also specify custom request and
response headers they want to log.

Add proto format details to AccessLog specification.

---

.travis.yml
api/rlds.proto
ci/do_ci.sh
test/build/BUILD
test/build/build_test.cc

This is useful in Travis CI (and also internally at Google in our CI) to
validate basic build/link of the protos.
This exposed a small issue with API compatibility. Since we don't have
additional package namespaces for each individual API, there was a
conflict between the RateLimit mesage in RLDS and RDS. The quick fix was
to move the RLDS message inside the response object (this is fine as
nobody is using the v2 RLDS yet, open to alternatives including per-xDS
API namespaces).

test/api: basic C++ build/link test, minor RLDS fix.

---

api/cds.proto
api/eds.proto
api/hds.proto
api/lds.proto
api/rds.proto
api/rlds.proto
test/build/build_test.cc

We can dynamically discover service/method descriptors in Envoy, so we
don't need to generate any C++ stubs for this. This simplifies the
Google import and removes an unnecessary build output.

api: remove cc_generic_services dependency.

---

api/BUILD
api/base.proto
api/bootstrap.proto
api/cds.proto
api/filter/http_connection_manager.proto

This patch adds a static bootstrap proto that is expected to be provided
on the filesystem or command-line. This should enable Envoy to then
either fetch the rest of config from disk or reach out to the various
management servers for the rest of the APIs.
Fixes #93.

api: static bootstrap proto definition.

---

api/accesslog.proto
api/base.proto
api/eds.proto
api/rds.proto
test/build/build_test.cc

* Add metadata to endpoints in EDS.
* Allow routes to specify a metadata_match. WeightedClusters can further
specify an additional metadata_match based on weighting.
* Log all metadata. It makes sense to have available to the logging
pipeline all metadata used during request processing, not just some
that is explicitly annotated. This then makes available the endpoint's
metadata for log consumption. The tradeoff is that this will increase
log sizes when metadata is plentiful. We may want to consider a way to
filter this in logs in the future.
Fixes #81 and #91.

eds/rds: endpoint subsetting in clusters based on metadata.

---

api/filter/http_connection_manager.proto
api/lds.proto

Direction is implied at the C++ type level, putting this in the config
is redundant and can making changes to the C++ implementations difficult
to synchronize between binary and config.
Fixes #63.

lds: eliminate direction from filter config.

---

api/cds.proto
api/health_check.proto

These arose while implementing v1 JSON -> v2 proto translation.

cds: some fixes to match the v2 protos with v1 schema and code.

---

README.md

We've committed to a bunch of work (and will continue to) beyond just
adding proto APIs and gRPC in v2. This PR is a move towards being more
systematic about tracking this going forward.

readme: written policy on how to track v2 implementation features.

---

api/eds.proto

This significantly simplifies EDS implementation in Envoy, as we can
have EDS updates propagates in the same way and with the same
gRPC/REST/filesystem watch infrastructure we use for LDS/RDS/CDS.

eds: split advanced LB stats and assignment streams.

---

api/eds.proto

Some TODOs were left behind in #11. The proposed scheme here avoids the
management server needing to compute precise percentages.

eds: clarify load balancing weights and effective traffic percentage.

---

api/rds.proto

There is room to grow the affinity policy now to arbitrary hashing on
connection properties (e.g. 3 tuple, 5 tuple, etc.) but we only care
about source IP address today.
Fixes #69.

rds: add source IP and (generated) cookie hash policies.

---

api/cds.proto

This effectively replaces the "features" field in the v1 JSON.

cds: clarify the role of set vs. unset http2_protocol_options.

---

api/BUILD
api/cds.proto
api/filter/http_connection_manager.proto
api/protocol.proto

Avoid false dependency on CDS by HTTP connection manager. This also
manifests at the code level when implementing v1 -> v2 translation.

cds/protocol: split out shared frontend/backend protocol options.

---

api/eds.proto

Fix a bug where the locality field of UpstreamLocalityStatus was a string instead of a Locality message.

Change locality field to Locality object for UpstreamLocalityStats

---

api/protocol.proto

I also renumbered existing variables.  I know this isn't something which should normally be done but as we're not using v2 yet I assume we don't need to be backwards compatible so I figured I'd keep it clean.

Removing unused per_stream_buffer_limit_bytes

---

api/cds.proto

At Google, we need to support cluster queries that contain ':', so this
seems a useful feature to retain in v2 as a means to do that (rather
than trying to retrofit this to the internal cluster naming in Envoy).

cds: promote service_name from deprecated to supported.

---

api/base.proto

Since we expected both node name and cluster in v1, it makes sense to
continue providing this to management servers. We don't need to use
metadata for cluster if it is required.

base: add cluster to Node and clarify what is required.

---

api/cds.proto

Add code points for original dst service discovery and load balancer
types, as well as for the cleanup interval configuration option. These are needed for Envoy PR 1246.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

api/cds.proto: Add cluster service discovery type for original dst.

---

api/bootstrap.proto

For envoy/#1411
Adding it in a structured proto because in the long run I anticipate us wanting to have per-cluster port ranges we bind to and it makes sense to me if we're going to eventually allow the bootstrap and cluster config to interact that we stick all the interacting bits in another message.
If this is over-designing I can make it a straight up address and we can link with documentation in future :-)

Adding a "bind to address" to the bootstrap proto

---

api/rds.proto

This completes the RDS API changes needed for the v1 JSON translation.

rds: add missing validate_clusters/use_websockets.

---

api/eds.proto

Previously, we had a complex way of inferring total error requests from
map value aggregation. This PR removes the error maps for now, providing
simple scalar totals instead. This will simplify
https://github.com/lyft/envoy/issues/1286.
We expect to add the error maps as an additional mechanism, orthogonal to
the scalar totals, later on, as standard proto extension.

eds: make UpstreamLocalityStats work with scalar totals.

---

api/address.proto

We can just try parse IPv6, and failing that do IPv4.

address: remove square brack requirements for IPv6.

---

api/BUILD

bootstrap: add dependency on ":address".

---

api/address.proto
api/base.proto
api/bootstrap.proto
api/cds.proto
api/lds.proto

Since we may want to use a resolver plugin in most places, it doesn't
make sense to have this strong separation between the two in the API.
Also bonus renumbering cleanup in LDS.

address: merge Resolved/Unresolved address types.

---

api/address.proto
api/bootstrap.proto
api/cds.proto

This doesn't include adding config config to the listener address.  
aside: do we allow resolving pipes or should we have a class wrapping the resolver and the socket address?

global and cluster-local bind config

---

README.md
api/BUILD
api/address.proto
api/bootstrap.proto
api/rls.proto
test/build/BUILD
test/build/build_test.cc

This is a design-level update to bootstrap.proto, that plumbs in the
remaining top-level config from v1. It will probably have some small
changes made beyond this as we implement.
Notable differences to v1 are:
* Static/dynamic resources are clearly delineated at top-level, clusters
no longer belong to the ClusterManager object.
* Stats sinks are a repeated list of opaque configs, similar to filter.
* Some simplifications to object types, e.g. RLS no longer specifies
type (do we want to preserve the v1 generality here?).
Also renamed RLDS back to RLS, I'll admit that it didn't make sense to
cram it into the xDS namespace, it's really a very distinct service on
the data plane and shouldn't be bundled with the control plane services.

bootstrap: v1 parity with static config.

---

api/bootstrap.proto

After #156 RateLimitDiscoveryService was renamed RateLimitService. This type collides with the type in the bootstrap.proto file.

fix ratelimit name collision

---

api/base.proto

Needed for empty resource responses to allow the xDS API the response is
pointing at to be identified. In non-empty resource responses, the
type_url is embedded in the Any messages.

ads: add type_url to DiscoveryResponse.

---

api/discovery.proto

This is a fix for a potential race that exists in the gRPC
implementation today. Namely:
1. Envoy sends a DiscoveryRequest at X with resources {A, B}
2. Management server responds with DiscoveryResponse at X+1.
3. Envoy decides (for whatever reason) to change resources before
beceiving the X+1 response. It sends a DiscoveryRequest at X
with {A, B, C}.
4. Management server treats the X DiscoveryRequest update as a NACK
for the X+1 DiscoveryResponse.

grpc: add explicit nonce to DiscoveryResponse.

---

api/bootstrap.proto

bootstrap: specify optional EDS load stats endpoint in ClusterManager.

---

api/bootstrap.proto

Add regex expressions to extract tags from stats names.
There is going to be a relatively long list of default tags (coupled with regexes) in Envoy (maybe 22 or so).  I wanted to see what people think about adding an extra option to just use all the defaults rather than being forced to specify each one individually in the config.

Add regex option for stats tags

---

api/cds.proto

Provides a configuration point for a load balancer that can divide endpoints into subsets addressable by route metadata.
See discussion in envoyproxy/envoy#1279.

cds: config for load balancer subsets

---

api/cds.proto

Updates the comment to reflect the design decision made in envoyproxy/envoy#1735 and renames `subset_keys` to `subset_selectors`.
My reasoning for the rename is that the field is all about determining how endpoints are grouped into subsets. Using the names of metadata keys in the endpoints is only one way and others might be added.

cds: rename field, update comments to match design choices

---

api/sds.proto

oneof doesn't provide any namespace scoping, so the names looked
too generic where they're used in implementations.

Give tls session ticket key fields better names.

---

api/eds.proto

Envoy decides to drop (circuit break, drop overload) at the cluster
rather than locality level.
This is a breaking change at the wire level, but the EDS load report API
has not yet been frozen.

eds: switch total_dropped_requests from locality to cluster.

---

.travis.yml
api/BUILD
ci/build_setup.sh
ci/ci_steps.sh
ci/do_ci.sh
tools/protodoc/BUILD
tools/protodoc/protodoc.bzl
tools/protodoc/protodoc.py

Mostly Bazel hacking to get a protoc plugin running against the
proto_library graph. The Python plugin doesn't actually do any RST
generation yet, it just runs against each file and dumps the input
proto.
The tool can be run with:
bazel build //api --aspects \
tools/protodoc/protodoc.bzl%proto_doc_aspect --output_groups=rst

docs: skeleton for RST documentation generation plugin.

---

api/base.proto
docs/build.sh
tools/protodoc/protodoc.py

* Support for enums, nested messages, oneof and map types.
* External links for scalar and WKT types.

protodoc: additional features to generate base.proto.

---

api/cds.proto

In response to https://github.com/envoyproxy/envoy/pull/1806 and
https://github.com/envoyproxy/envoy/pull/1871.

cds: update cluster name restrictions in Cluster.

---

api/filter/network/BUILD
api/filter/network/tcp_proxy.proto

Until the SNI feature arrives, we need this in order to have a usable V2 API plane. I have retained the configuration format as is (comma separated port list, etc.) so as to get a working implementation first.
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>

tcp route config

---

api/rds.proto

*Description*:
- Allow for redirect actions to specify which response code to use. Ex: some routes want to return a 302 instead of the default 301.
- Update documentation around TLS redirect response code to reflect code behavior.

redirect: allow to specify redirect response code

---

api/base.proto
api/rds.proto

Provides API support for envoyproxy/envoy#2002 and fixes comment related to envoyproxy/envoy#2003.

RDS: add response_headers_to_add/remove fields in VirtualHost and RouteAction

---

docs/publish.sh

I changed my mind. This will work better with other projects later.
I will clean up all the stale docs in the website repo once we are
fully converted to the new system.

docs: change publish path

---

docs/root/configuration/http_conn_man/headers.rst

fix typo in x-forwarded-client-cert description

---

api/address.proto
api/base.proto
tools/protodoc/protodoc.py

* [#not-implemented-hide:] will hide a message/enum/field from docs.
* [#not-implemented-warn:] will add a "Not implemented yet" warning to a
message/enum/field.
* [#v2-api-diff:<text>] will add a note indicating v2 API difference to
a message/enum/field.
* Switched title annotation to [#protodoc-title:<text>] for consistency.

protodoc: some extra annotations.

---

WORKSPACE

Matches https://github.com/envoyproxy/envoy/pull/2064
Signed-off-by: John Millikin <jmillikin@stripe.com>

Update protobuf dependency to 3.5.0.

---

api/BUILD
api/filter/accesslog.proto
api/rds.proto
docs/build.sh
docs/root/api-v2/filter/http/http.rst

This PR just fixes enough stuff to get the HTTP connection manager filter
docs building. I want to get this out as it conflicts with other inflight
PRs and some of the work can be split up. E.g., access logging with that
in flight PR.

docs: get HTTP connection manager building

---

api/eds.proto

As discussed and docced up here:
https://github.com/envoyproxy/envoy/pull/1980#issuecomment-341436710
My one remaining concern with this approach is that the clusters all take a cluster config on start-up so they won't all get the benefits of primary/failover mechanics.  It looks like static already doesn't get priorities so maybe it's meant to be a super simple start-up option but it seems like it still might benefit from the more advanced features. 
For  #1929

Replacing failover with priorities

---

api/eds.proto

Having priority a a property of the enpoint gets messy on the coding side.  It's easier if endpoints are grouped by [weight / priority / locality]
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>

moving priority to lbendpoint

---

docs/root/operations/admin.rst

This PR is related to https://github.com/envoyproxy/envoy/pull/2026.
You also need `sphinx-rtd-theme` for the docs to build.

docs: add docs for prometheus stats

---

api/BUILD
api/filter/accesslog/BUILD
api/filter/accesslog/accesslog.proto
api/filter/http/BUILD
api/filter/http/router.proto
api/filter/network/BUILD
api/filter/network/http_connection_manager.proto
api/filter/network/tcp_proxy.proto
docs/build.sh
docs/root/api-v2/filter/filter.rst
test/build/BUILD
test/build/build_test.cc

This avoids things like `filter.OrFilter` which makes no sense.

move accesslog.proto to dedicated namespace

---

BUILD
api/BUILD
api/filter/BUILD
api/filter/accesslog/BUILD
api/filter/http/BUILD
api/filter/network/BUILD

Gogoproto is not supported natively by bazel, and requires extra hackery that is best kept hidden in the consumer of the repo.
Note that rules_go are still imported as protoc-gen-validate does not build without them.

Remove rules_go

---

api/cds.proto

Rather than opening an issue, I figured it would just make sense to discuss this in this PR as it's a relatively small addition.  
We'd like to add a metadata field to CDS and have it be accessible in Envoy through [ClusterInfo](https://github.com/envoyproxy/envoy/blob/master/include/envoy/upstream/upstream.h#L275) and anywhere else general cluster info is available.

Add metadata field to Cluster in CDS

---

docs/root/install/sandboxes/zipkin_tracing.rst

Signed-off-by: Daljeet Virdi <daljeetv@gmail.com>
Description: The link to Zipkin dashboard was incorrect.
Risk Level: Low
Testing: tested locally.

Zipkin Dashboard URL link should use docker-machine ip.

---

api/BUILD
api/address.proto
api/base.proto
api/cds.proto
api/eds.proto
api/filter/http/fault.proto
api/filter/http/health_check.proto
api/filter/http/lua.proto
api/filter/http/transcoder.proto
api/filter/network/http_connection_manager.proto
api/filter/network/mongo_proxy.proto
api/filter/network/redis_proxy.proto
api/filter/network/tcp_proxy.proto
api/health_check.proto
api/lds.proto
api/protocol.proto
api/rds.proto
api/sds.proto
bazel/api_build_system.bzl
bazel/repositories.bzl
test/validate/BUILD
test/validate/pgv_test.cc
test/validate/test.proto
tools/protodoc/protodoc.py

* Added PGV C++ generation support. This (hopefully temporarily)
abandons using native proto_library in favor of pgv_cc_proto_library.
We maintain build support for proto_library for the glorious future in
which we write a Bazel aspect to run PGV against the native
proto_library shadow graph.
* Replace min_len with min_bytes on strings, until PGV gets not-empty or
min_len support for C++.
* Various fixups for places where the PGV plugin objected to
annotations.

pgv: bazel plumbing for PGV support, some PGV related fixups.

---

api/bootstrap.proto
api/cds.proto
api/filter/accesslog/accesslog.proto
api/filter/network/http_connection_manager.proto
api/lds.proto
api/rds.proto

This is code movement only and no other changes. There should be
no namespace changes or effects to consumers.

docs: reorder protos for easier top down reading

---

XDS_PROTOCOL.md
docs/root/configuration/overview/v2_overview.rst

Links xDS earlier in API v2 overview. Removes line numbers from github xDS proto links. Modifies xDS protocol doc to more clearly define xDS at the start.

docs: minor edits for clarity

---

bazel/repositories.bzl

This picks up the weak link approach and a number of bug fixes needed
for C++ code generation.

pgv: bump version to 8e6aaf5.

---

api/base.proto

bootstrap: relax some node constraints for fields that are set by Envoy.

---

api/address.proto

statsd can send to UDP addresses.

address: relax UDP constraint on SocketAddress.

---

docs/root/intro/version_history.rst
docs/root/operations/admin.rst

Add information about the version info string in the `/clusters` admin endpoint.

docs: add version info docs for /clusters admin endpoint

---

API_OVERVIEW.md
api/filter/README.md
docs/README.md
docs/root/api-v1/cluster_manager/cluster.rst
docs/root/api-v1/listeners/listeners.rst
docs/root/api-v1/network_filters/http_conn_man.rst
docs/root/api-v1/network_filters/tcp_proxy_filter.rst
docs/root/api-v1/route_config/route.rst
docs/root/api-v1/route_config/vhost.rst
docs/root/configuration/access_log.rst
docs/root/configuration/cluster_manager/cluster_runtime.rst
docs/root/configuration/http_filters/router_filter.rst
docs/root/configuration/overview/v1_overview.rst
docs/root/configuration/overview/v2_overview.rst
docs/root/configuration/runtime.rst
docs/root/install/sandboxes/front_proxy.rst
docs/root/install/sandboxes/jaeger_tracing.rst
docs/root/install/sandboxes/zipkin_tracing.rst
docs/root/intro/arch_overview/outlier.rst
docs/root/intro/arch_overview/redis.rst
docs/root/intro/arch_overview/service_discovery.rst
docs/root/intro/arch_overview/ssl.rst
docs/root/intro/arch_overview/threading_model.rst
docs/root/intro/comparison.rst
docs/root/operations/cli.rst
tools/check_format.py

Removing extra whitespace from rst / md.
Hopefully the last format tweaks until I sort out how to merge the two sets of scripts :-)
Noteworthy: the changes to the tables.    I think they all look "good enough" but we could explicitly exempt ellipses to prevent them from being rewritten if anyone cares.

Removing extra whitespace from rst / md

---

api/address.proto

To resolve https://github.com/envoyproxy/envoy/issues/2155, it seems
better to fix via docs than implementation. This is because we have a
choice of binding 0.0.0.0 or ::, and the current Envoy idiom is to make
the user be explicit rather than probe.
It's possible to use :: for both IPv4/v6, for example, in
certain environments where /proc/sys/net/ipv6/bindv6only is set to 0. We
could add support to Envoy and the API for IPV6_V6ONLY to override this,
but this is orthogonal to the above issue.

address: make bind any explicit.

---

api/address.proto
api/base.proto
api/cds.proto
api/filter/accesslog/accesslog.proto
api/rds.proto
tools/protodoc/protodoc.py

These were lost in my backlog. Required a PGV fix for cross-package enum
validation to deal with the TODOs, see
https://github.com/lyft/protoc-gen-validate/issues/42.

api: add some missing enum.defined_only constraints.

---

api/address.proto

This is the same as haproxy's v4v6 bind option:
https://serverfault.com/questions/747895/bind-to-all-interfaces-for-ipv4-and-ipv6-in-haproxy.

address: support IPv4/IPv6 dual bind.

---

api/base.proto
docs/root/operations/cli.rst

This patch clarifies the relationship between the CLI flags for local
service configuration and the bootstrap node identifier, where these
concepts are also expressed.

docs: update --service-{node,cluster,zone} to the v2 world.

---

docs/root/configuration/http_conn_man/headers.rst

Provides documentation for the changes related to envoyproxy/envoy#2148.

docs: document UPSTREAM_METADATA header variable

---

api/filter/http/BUILD
api/filter/http/gzip.proto

- missing import for wrappers
- cannot have two enums with same NAME

Small fix for Gzip proto

---

api/cds.proto
api/sds.proto
docs/root/intro/arch_overview/ssl.rst

CertificateValidationContext.trusted_ca is not only for client
certificates, but also for server certs. Change the wording to "peer
certificates".
Also mention that verification is not enabled by default in docs for
UpstreamTlsContext.

Clarify docs on trusted_ca

---

api/BUILD
api/auth/BUILD
api/auth/auth.proto
api/auth/external_auth.proto
api/external_auth.proto
api/rds.proto
bazel/api_build_system.bzl
bazel/repositories.bzl

This PR proposes an external auth filter API with the following characteristics.
1. All information related to authorization is schematized.
2. Information is schematized without using envoy-specific abstractions.
3. The api is aligned with Istio Authorization Check (Mixer Check) api.
4. Adds `map<string, string> request_context` to pass additional information to the server.
This is proposed as an alternative to https://github.com/envoyproxy/data-plane-api/pull/222

External auth filter2

---

api/filter/accesslog/accesslog.proto

1) Use Address instead of SocketAddress to account for UDS.
2) Rename/clarify/add both remote/local for downstream/upstream.

access log: small fixes

---

api/filter/accesslog/accesslog.proto

This is needed for more accurate time accounting. In general I noticed that we were not
accounting for total duration / last byte sent. I opted for adding detailed timings in both 
directions as I think if implemented this would make it much easier to visualize filter activity,
buffering vs. streaming, etc.

access log: add additional downstream tx time fields

---

api/filter/http/gzip.proto

This PR includes a change to ```gzip.proto``` which makes window_bits (compressor's window size) also configurable. The change will allow a less opinionated and more flexible compression filter.

Filter: Added window_bits field to gzip proto

---

api/auth/external_auth.proto

This PR eliminates `Request` as a separate message and moves the definition as an inline `oneof`.
The advantage of this approach is that on the policy authoring side the most common form of http request becomes `attributeContext.request` instead of `attributeContext.request.http_request`
Other forms of requests can be added later as `attributeContext.redis_request`, etc.
Signed-off-by: Mandar U Jog <mjog@google.com>

Move request.http_request to ac.request in envoy.api.v2.auth package.

---

docs/root/intro/comparison.rst

I didn't remove the HTTP/2 reference as Haproxy 1.8 only supports it on the frontend, not for backend communication.

docs: remove incorrect information concerning haproxy's capabilities

---

api/sds.proto
docs/root/api-v1/listeners/listeners.rst

Required in order to verify CRLs in Envoy.
Duplicate of #249
cc @mattklein123

Add "crl" field to CertificateValidationContext

---

docs/root/operations/cli.rst

This reverts commit 06ae0116c145f1ef702cab24907f40eabdd22693 and PR https://github.com/envoyproxy/data-plane-api/pull/361.
Decided not to implement `--stat-tag` CLI arg, https://github.com/envoyproxy/envoy/pull/2264. ref: https://github.com/envoyproxy/envoy/pull/2264#issuecomment-354011600.

stats: revert docs for new `--stat-tag` CLI arg (#361)

---

api/BUILD
api/auth/external_auth.proto
api/filter/http/BUILD
api/filter/http/ext_authz.proto
api/filter/network/BUILD
api/filter/network/ext_authz.proto
api/grpc_cluster.proto

Add support for configuration of TCP, HTTP filters to support external authorization cluster.
The filter configuration references an external cluster which is expected to be running the grpc server that supports the service being defined by https://github.com/envoyproxy/data-plane-api/pull/296
cc: @mandarjog, @wora, @spikecurtis

Add tcp and http filter for external authorization checker grpc server.

---

api/base.proto
docs/root/api-v1/listeners/lds.rst
docs/root/api-v1/route_config/rds.rst

https://github.com/envoyproxy/envoy/pull/2256 adds restrictions to the backing sources for xDS resources. This change documents those restrictions.

xDS: add docs about backing source restrictions

---

api/cds.proto

cds: correct dns_lookup_family default docs.

---

api/rds.proto

This diff unhides the docs now that the feature has been implemented in envoy.

Unhide the query parameter match routing from the docs

---

XDS_PROTOCOL.md
docs/root/api-v1/http_filters/squash_filter.rst
docs/root/configuration/access_log.rst
docs/root/configuration/http_conn_man/headers.rst
docs/root/configuration/http_filters/squash_filter.rst
tools/check_format.py

When I did the "ignoring tables" change I actually broke it :-(
Fixing with real python regex.  Also bonus complaining if there's trailing whitespace because otherwise fix_format fixes things check_format didn't whine about which results in files you didn't touch changing.

Fixing fix format

---

api/health_check.proto

Part of the work on
https://github.com/envoyproxy/envoy/issues/369

GRPC-native healthcheck config option

---

api/filter/network/http_connection_manager.proto

I have a pull request ready for Envoy as well that I could submit without tests until this gets merged and I can add end to end integration tests.  This is also my first contribution to envoy, but I didn't see any mention of a need to sign a CLA but am happy to do so if required.

Add an option to forward the base64 encoded cert through the xfcc header

---

STYLE.md

This is a common disagreement within existing APIs. We should avoid this issue.
Signed-off-by: Hong Zhang <wora2000@gmail.com>

Use upper camel case names for type names

---

api/grpc_service.proto

We need to track statistics in a client neutral way, since the Google
gRPC client doesn't have upstream stats. This will allow us to track the
gRPC status returned by the remote (or inferred from events such as
client timeouts).

grpc_service: add stat_prefix field.

---

api/cds.proto

Currently clusters can not open both HTTP1.1 and HTTP2 upstream
connections at the same time.  When the new cluster option
"auto_http2" is set to "true", the cluster must open an HTTP2 upstream
connection if the downstream connection is HTTP2, and an HTTP1.1
upstream connection if the downstream connection is HTTP1.1. This option
is to have no effect if there is no corresponding downstream
connection.
This functionality removes the need to operate multiple clusters and
routing rules for them when the backends accept both HTTP1.1 and HTTP2
connections, and when the choice of the HTTP protocol is significant,
as with gRPC.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

cds: Add "auto_http2" option.

---

api/BUILD
bazel/api_build_system.bzl
test/build/BUILD

Created new definitions in api_build_system.bzl that wrap
go_proto_library, go_grpc_library, and go_test. Changed rules in api/BUILD and
test/build/BUILD to use these new definitions. In the future these
definitions could be expanded upon for auto generation in api_proto_library.
Signed-off-by: Kyle Myerson <kmyerson@google.com>

Refactor go BUILD targets.

---

api/cds.proto

This is the corresponding doc change for an Envoy update to make the CDS metadata field accessible in ClusterInfo.

cds: remove cds metadata not-implemented tag

---

docs/root/configuration/overview/v2_overview.rst
docs/root/intro/arch_overview/grpc.rst

Fix `cluster_name` vs `cluster_names` typo in examples and G++ vs C++ in GRPC overview.

docs: fix misnamed field in examples and g++ vs. c++

---

api/base.proto

In golang, protoc needs all files in the same directory to belong to the same package. 
This PR forces all compiled protos in the root directory to belong to the `api` package.

go: override root level package name

---

docs/root/configuration/http_filters/router_filter.rst

This patch adds doc for adding gateway-error as a retry-on policy, i.e. when the received response code is classified as a gateway error (502, 503 and 504). It is a subset of 5xx.
Ref: https://github.com/envoyproxy/envoy/issues/2300

docs: add gateway-error as one of retry-on policies

---

api/stats.proto

For https://github.com/envoyproxy/envoy/issues/1975.
Adding extra fields to TagSpecifier to allow users set default tags
which have a fixed value.
Envoy side PR: https://github.com/envoyproxy/envoy/pull/2357.

stats: support default tags with fixed value

---

docs/root/operations/admin.rst

Documents the `/runtime` admin endpoint added for read-only access to the current runtime values.
Related: https://github.com/envoyproxy/envoy/pull/2353

admin: document /runtime endpoint

---

STYLE.md
api/base.proto
api/filter/http/BUILD
api/filter/http/health_check.proto

*Description*:
Extend the "non pass through" mode of the HTTP health check filter to allow an
optional map from cluster names to percentages. If specified, each of the named
clusters must have at least the specified percentage of its servers healthy for
the filter to return a 200. (The proxy also must be in a non-draining state, or
else the filter will return a 503 like it did previously.)
Associated envoyproxy/envoy issue: https://github.com/envoyproxy/envoy/issues/2362

Healthcheck filter: compute response based on upstream cluster health

---

docs/root/configuration/http_filters/lua_filter.rst

I've added a notice to the lua filter related to how it's built and linked and that a user wishing to load modules installed with luarocks would need to build envoy with exported symbols.
Signed-off-by: Nicholas J <nicholas.a.johns5@gmail.com>

Docs: add notice related to lua and exported symbols

---

api/BUILD
api/trace_service.proto
bazel/repositories.bzl

This is a trace service proposal based on the opencensus (opencensus.io) data model. OpenCensus is an vendor independent tracing (support for zipkin, stackdriver, and soon others) and stats library(prometheus, stackdirver, signalfx, and soon others), integrated in products like gRPC (grpc.io).
One of the usages will be in the Istio (istio.io) environment to push traces to the Mixer.
/cc @douglas-reid @louiscryan

Add Trace Service Support.

---

api/filter/http/health_check.proto
docs/root/intro/arch_overview/health_checking.rst

*Description*:
Update the HTTP health check filter documentation to match Envoy PR [2387](https://github.com/envoyproxy/envoy/pull/2387)
Associated envoyproxy/envoy issue: [2362](https://github.com/envoyproxy/envoy/issues/2362)

docs: add new percentage-based response option to health check filter

---

api/rds.proto
docs/root/api-v1/route_config/route_config.rst
docs/root/configuration/http_conn_man/headers.rst

Matches changes related to envoyproxy/envoy#2250. Plus some formatting fixes in the header variable definition list.

docs: update custom header docs to match envoy behavior

---

api/trace.proto
docs/root/api-v1/tracing.rst

Add options for specifying a tracing library to load dynamically (See also https://github.com/envoyproxy/envoy/pull/2252.)

tracing: Support dynamically loading tracing libraries.

---

api/lds.proto

Remove not implemented tag from lds metadata because it will be used in an upcoming PR.

remove not implemented tag from lds metadata

---

api/rds.proto

* envoyproxy/envoy#2371
I'm not sure if it's worth stating somewhere that this would be used to swap `http` for `https` in most cases?

Add scheme_redirect to RedirectAction

---

docs/root/configuration/http_conn_man/traffic_splitting.rst
envoy/api/v2/route/route.proto

Update documentation to match implementation in envoyproxy/envoy#2440.
Makes the WeightedCluster.total_weight field visible in documentation. Update ClusterWeight.weight and traffic shaping document to match.

docs: make WeightedCluster.total_weight visible

---

docs/root/intro/arch_overview/ssl.rst
envoy/api/v2/auth/cert.proto

As requested in: https://github.com/envoyproxy/envoy/pull/2255

Add CRL support to architecture overview

---

envoy/api/v2/route/route.proto

Add request_headers_to_add and response_headers_to_add to ClusterWeight.
The directives are processed when the cluster in selected through the enclosing RouteAction.
reference: https://github.com/envoyproxy/envoy/issues/2455
Signed-off-by: Mandar U Jog <mjog@google.com>

Add *_headers_to_add to `ClusterWeight`

---

docs/root/configuration/access_log.rst
docs/root/configuration/http_conn_man/headers.rst

Document 
* DOWNSTREAM_LOCAL_ADDRESS
* DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT 
as header and access log variables.
Related to https://github.com/envoyproxy/envoy/pull/2487

Document DOWNSTREAM_LOCAL_ADDRESS header variable

---

envoy/api/v2/filter/network/http_connection_manager.proto

This PR adds trace sampling controls to the public API. It is a continuation of work from PR #375.
The controls added:
- `Tracing.sampling` (equivalent to [tracing.global_enabled](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/runtime.html?highlight=global_enabled))
- `Tracing.random_sampling` (equivalent to [tracing.random_sampling](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/runtime.html?highlight=random_sampling))
Signed-off-by: Douglas Reid <douglas-reid@users.noreply.github.com>

Expose trace sampling controls

---

docs/root/configuration/http_filters/lua_filter.rst

This patch fixes a small typo in the lua `headers:replace` API doc.
Signed-off-by: Dhi Aurrahman <dio@hooq.tv>

docs: fix typo lua headers replace API

---

envoy/api/v2/core/address.proto

This is a follow up to https://github.com/envoyproxy/envoy/pull/2512

address.proto: added doc for abstract sockets

---

envoy/config/filter/http/gzip/v2/gzip.proto

In this PR:
1) disable_on_last_modified_header has been removed. This option is not fundamentally important for the filter, and it can be added later if requested. 
2) As per slack conversation with @jmarantz, we decided to re-include remove_accept_encoding_header. This option was part of the initial design, and it allows the filter to strip off accept-encoding before dispatching the headers to the upstream.
3) Few grammar corrections.
The filter has been approved. These are the final doc and configuration changes before the release.

gzip_filter: dropped disable_on_last_modified_header and re-included remove_accept_encoding_header

---

envoy/api/v2/route/route.proto
envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto

For envoyproxy/envoy issue [#2503](https://github.com/envoyproxy/envoy/issues/2503)

enable configuration of the number of trusted addresses in XFF

---

WORKSPACE

For whatever reason, `bazel fetch` needs this resource defined while `bazel build` does not 😕. I would like to be able to run `bazel fetch` to fetch external dependencies without having to build the C++ or Go protobuf binaries.
cc: @htuch

Fix bazel fetch command by providing //external:python_headers

---

envoy/api/v2/core/grpc_service.proto

Google has some internal customizations that require configuration to be
provided. Added a generic site local customization field.

grpc: add opaque config for GoogleGrpc.

---

envoy/config/filter/http/ext_authz/v2/ext_authz.proto
envoy/config/filter/network/ext_authz/v2/ext_authz.proto

_Title_
Fix up the comments for `failure_mode_allow` that was incorrectly worded and caught during review https://github.com/envoyproxy/envoy/pull/2416
cc: @junr03 
PS: I removed the comment about the restriction to only envoy_grpc client. That limitation is not really applicable based off the comment by Harvey in the PR#2416. Please do let me know if think it should be there.

External authorization review comments

---

envoy/api/v2/cds.proto

This adds ability to configure settings for zone aware load balancing settings as config options.
solves https://github.com/envoyproxy/envoy/issues/1344 
Changes : Added min_cluster_size and enabled_percentage to commonLbConfig which enables them to used directly in load_balancer_impl.cc
Signed-off-by   : sri kailash  <sri.gandebathula@booking.com>

Adds ability to configure ZoneAwareLoadBalancing settings as config options 

---

envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.proto

The link wasn't quite correct for linking back to the filter
documentation. This PR just points it to the right place.

Fix reference to using deprecated_v1 in tcp_proxy

---

docs/root/operations/cli.rst

This is the update to the documentation that's required once the `--disable-hot-restart` cli flag PR is merged. See https://github.com/envoyproxy/envoy/pull/2576.

docs: Add description for --disable-hot-restart cli flag

---

docs/root/configuration/overview/v2_overview.rst

doc: fix data-plane-api link in v2_overview.rst.

---

docs/root/api-v1/cluster_manager/cluster_hc.rst
docs/root/intro/arch_overview/health_checking.rst
envoy/api/v2/core/health_check.proto

There is no way to modify the response of PING on a running Redis server without restarting it. This makes it painful to terminate an instance. All inflight requests plus requests until ejection by active or passive healthcheck will fail.

alternate redis healthcheck

---

envoy/api/v2/core/grpc_service.proto

Useful when supporting simple header value auth schemes across gRPC
client types.

grpc_service: initial_metadata support.

---

docs/root/install/distro/ambassador.rst
docs/root/install/getting_started.rst

This PR adds a new section to the Getting Started guide entitled "Other Use Cases" which show how Envoy can be used in specific situations. The thought is that users may want to use an Envoy distribution instead of Envoy itself for specific scenarios.
I also added a tutorial on how to use the open source Ambassador project to deploy Envoy as an API Gateway in Kubernetes, with an example that mirrors the google smoketest that is also used in the getting started.

Update Getting Started guide with open source distro section

---

bazel/api_build_system.bzl
docs/root/api-v1/access_log.rst
docs/root/configuration/cluster_manager/cluster_hc.rst
docs/root/configuration/http_conn_man/stats.rst
docs/root/configuration/http_filters/grpc_http1_bridge_filter.rst
docs/root/configuration/tools/router_check.rst
docs/root/install/sandboxes/front_proxy.rst
docs/root/install/tools/route_table_check_tool.rst
docs/root/operations/admin.rst
envoy/api/v2/cds.proto
envoy/api/v2/endpoint/load_report.proto
envoy/config/filter/accesslog/v2/accesslog.proto
tools/protodoc/protodoc.py

I found this neat tool when looking through another open-source project: https://github.com/client9/misspell. Ran it over the docs for fun. Didn't give any false positives!

fix spelling mistakes

---

XDS_PROTOCOL.md

Changed the links in` xds_protocol.md` to use doc references rather than source references.

change xds proto doc links to use docs

---

XDS_PROTOCOL.md
tools/protodoc/protodoc.py

@htuch looks like the doc link for `error_detail` because of line spacing. Corrected that and also `grpc.rpc.Status` link is not coming. Changed the .py file add this. PTAL.

docs:fix doc links

---

envoy/api/v2/cds.proto
envoy/api/v2/eds.proto
envoy/api/v2/lds.proto
envoy/api/v2/rds.proto
envoy/api/v2/route/route.proto
envoy/service/accesslog/v2/als.proto
envoy/service/auth/v2/external_auth.proto
envoy/service/discovery/v2/ads.proto
envoy/service/discovery/v2/hds.proto
envoy/service/load_stats/v2/lrs.proto
envoy/service/metrics/v2/metrics_service.proto
envoy/service/trace/v2/trace_service.proto

This enables generating generic service stubs for all the data-plane-api
proto services when generating Java classes with protoc.
This is generally not needed when implementing a gRPC server but in our case we're implementing
it behind our legacy protobuf RPC framework which rely on these stubs. As far as I know the only negative
with enabling these is generating some potentially unnecessary Java classes.

Add java_generic_services option to service proto files

---

envoy/config/filter/accesslog/v2/accesslog.proto

_Title_
In the proxy we've added an `Unauthorized` response flag. This PR adds the same to filter access logs.
Once this PR is merged it will be possible to set the flag in `source/common/access_log/grpc_access_log_impl.cc`
See also, comment in https://github.com/envoyproxy/envoy/pull/2415
cc: @htuch
Signed-off-by: Saurabh Mohan <saurabh+github@tigera.io>

Add unauthorized boolean the accesslog.

---

envoy/type/percent.proto

Missing another Equals annotation from a type.
It might be worth enabling Equals for the entire API, to avoid patching this frequently. 

go: add equals to percent

---

envoy/config/filter/network/tcp_proxy/v2/BUILD
envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.proto

This should allow the tcp proxy to target a specific subset of endpoints
in a cluster by matching on the metadata, similar to what is currently
possible in the http_connection_manager filter.
See https://github.com/envoyproxy/envoy/issues/2696
Signed-off-by: Snow Pettersen <snowp@squareup.com>

tcp proxy: add metadata_match to tcp proxy config

---

docs/root/configuration/access_log.rst
docs/root/configuration/http_conn_man/headers.rst
docs/root/intro/arch_overview/service_discovery.rst
envoy/api/v2/lds.proto

Add a "transparent" option to Listener to set the SOL_IP/IP_TRANSPARENT option on listen sockets, which allows using Envoy with the iptables TPROXY target.
Unlike the iptables REDIRECT target, TPROXY allows preserving both the source and destination IP addresses and ports of accepted connections.
API changes for: https://github.com/envoyproxy/envoy/pull/2719
Signed-off-by: Romain Lenglet <romain@covalent.io>

lds: Add "transparent" option to support iptables TPROXY in listeners

---

envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto

I was having trouble generating docs locally `./docs/build.sh: line 92: sphinx-build: command not found`.  It also wasn't totally clear if I should only be documenting this in the protofile and then it would be picked up by the v2 docs, or if I should also be documenting this in rst files in the v1 documentation folders.  If this isn't enough, please let me know and I'll improve things.

Document cert forwarding in the XFCC header.

---

docs/root/configuration/http_conn_man/headers.rst
envoy/api/v2/route/route.proto

Unhide the `request_headers_to_add`, `response_headers_to_add`, and `response_headers_to_remove` fields in ClusterWeight. Update HTTP conn manager docs related to same.
Doc update for envoyproxy/envoy#2765.

docs: weighted cluster route manipulation

---

envoy/api/v2/core/address.proto
envoy/api/v2/lds.proto

Add an option "freebind" in LDS for listeners and the BindConfig which
is used for outgoing upstream connections. If true, set the IP_FREEBIND
socket option. Defaults to false.
PR description will be updated with Envoy implementation PR# once it is
created. Currently hidden as not implemented.
Signed-off-by: Dan Noé <dpn@google.com>

lds,BindConfig: Add "freebind" options to support IP_FREEBIND.

---

docs/root/configuration/cluster_manager/cluster_stats.rst
docs/root/intro/arch_overview/cluster_manager.rst

docs: add cluster warming information

---

envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.proto

This got implemented here https://github.com/envoyproxy/envoy/pull/2708
Signed-off-by: Snow Pettersen <snowp@squareup.com>

tcp proxy: Remove not-implemented for metadata_match

---

envoy/config/metrics/v2/stats.proto

This is a follow-up PR of https://github.com/envoyproxy/data-plane-api/pull/325.
I mistook to add an unnecessary field [here](https://github.com/envoyproxy/data-plane-api/pull/325#discussion_r155102953). What actually we need is just making `dog_statsd_specifier` `oneof` field, not adding `tcp_cluster_name` field.
We can safely drop this field because users has ended up with
initializing errors if they had specified this field.
```
[critical][main] source/server/server.cc:71] error initializing configuration '/envoy.yaml': Address must be a socket or pipe
```
This field has
never been used in envoy repo: https://github.com/envoyproxy/envoy/blob/7d03b231c7e8e086956096f6ca961f82c684ed0b/source/server/config/stats/dog_statsd.cc#L19-L23
Signed-off-by: Taiki Ono <taiki-ono@cookpad.com>

docs: drop unnecessary field in DogStatsdSink message

---

envoy/config/filter/fault/v2/fault.proto

I am working on a scala data plane, which I got a code generation error as the `oneof` named `fault_delay_type` will result in the same name with the enum `FaultDelayType`.
```
envoy/config/filter/http/ip_tagging/v2/ip_tagging.proto: warning: Import google/protobuf/wrappers.proto but not used.
--scala_out: envoy/config/filter/fault/v2/fault.proto: The sealed trait generated for the oneof 'fault_delay_type' conflicts with another message name 'FaultDelayType'.
[trace] Stack trace suppressed: run last data-plane/compile:protocGenerate for the full output.
[error] (data-plane/compile:protocGenerate) protoc returned exit code: 1
[error] Total time: 1 s, completed Mar 15, 2018 6:12:40 PM
```
Although this is valid in protobuf and looks a bug of scala protobuf, I think I still want a fix here. …

change the oneof naming of fault delay

---

docs/root/configuration/http_filters/grpc_http1_bridge_filter.rst

Due to there's actually no `HTTP/1.1` with gRPC format link. To avoid misunderstanding, I've adjusted the sequence and placed the **similar** wire format in gRPC over HTTP/2. The updated link is equivalent to wire format link in gRPC guide.
Ref to #555.
Signed-off-by: Tzu-Chiao Yeh <su3g4284zo6y7@gmail.com>

Fix broken grpc wire format link in http bridge doc.

---

docs/root/intro/version_history.rst
envoy/api/v2/core/health_check.proto

This enables the "no-traffic-interval" as supported by https://github.com/envoyproxy/envoy/pull/2835

Enable no-traffic-interval of health check config

---

docs/root/intro/arch_overview/statistics.rst
envoy/config/metrics/v2/stats.proto

Fixes https://github.com/envoyproxy/envoy/issues/2538
As discussed at https://github.com/envoyproxy/envoy/issues/2538#issuecomment-363493241, tagged metrics/statics should be coverd in the archtecture overview, since most uses start from it. I added some v1/v2 differences about stats sinks in arch overview and left the configuration page to describe which sink supports tagged metrics because we will have more sinks.
This is a draft one and any comments are welcomed about both the content and English matters.
cc @mrice32

docs: add documents about tagged metrics

---

docs/root/configuration/listener_filters/original_dst_filter.rst
docs/root/intro/version_history.rst
envoy/api/v2/lds.proto

Redefine the transparent and freebind listener options using
google.protobuf.BoolValue instead of bool.
Document the behavior when each option is set to true, set to false,
or unset.
Document that the transparent option should be used in conjunction
the original_dst_filter to restore the original destination address.
Mention the transparent option in version history.
Signed-off-by: Romain Lenglet <romain@covalent.io>

lds: Make listen socket options optional and improve docs

---

docs/root/configuration/cluster_manager/cluster_stats.rst
docs/root/configuration/configuration.rst
docs/root/configuration/http_conn_man/stats.rst
docs/root/configuration/http_filters/ip_tagging_filter.rst
docs/root/configuration/http_filters/router_filter.rst
docs/root/configuration/listeners/stats.rst
docs/root/configuration/network_filters/tcp_proxy_filter.rst
docs/root/configuration/statistics.rst

Add missing statistics documents reported at https://github.com/envoyproxy/envoy/issues/2713.
Fixes https://github.com/envoyproxy/envoy/issues/2713

 docs: add missing statistics documents

---

docs/root/intro/version_history.rst
docs/root/operations/admin.rst

This patch adds info of /stats/prometheus as an alternative endpoint to
get server stats in prometheus format.
Refs: 
- https://github.com/envoyproxy/envoy/issues/2182
- https://github.com/envoyproxy/envoy/pull/2896

docs: add /stats/prometheus as an alternative endpoint

---

docs/conf.py
docs/root/intro/version_history.rst
docs/root/operations/admin.rst

The endpoint docs could use a link to `config_dump.proto` docs but we're not going to worry about generating those quite yet. Probably after a couple more endpoints are converted.
Test plan: `./docs/build.sh`
Signed-off-by: James Sedgwick <jsedgwick@lyft.com>

docs: release note and docs for /config_dump admin endpoint

---

envoy/api/v2/core/address.proto
envoy/api/v2/lds.proto

This follows up from #558 which made IP_FREEBIND a BoolValue for LDS but
not for upstream. I think it makes sense to have it in both places given
the new socket options setup introduce in
https://github.com/envoyproxy/envoy/pull/2734.
Some bonus docs fixups thrown in.

BindConfig: make upstream and downstream bind config consistent.

---

envoy/config/filter/accesslog/v2/BUILD
envoy/config/filter/network/http_connection_manager/v2/BUILD

These are required to generate xDS responses from a Go binary. If they
don't exist, implementations are required to vendor the data-plane-api
with this change applied.
Signed-off-by: John Millikin <jmillikin@stripe.com>
cc @kshia

Add `api_go_proto_library` targets for HTTP connection manager protos.

---

docs/root/intro/version_history.rst
docs/root/operations/cli.rst

The list of format specifiers is derived from
https://github.com/gabime/spdlog/wiki/3.-Custom-formatting.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

docs: Document '--log-format' command line option.

---

docs/root/intro/version_history.rst
envoy/api/v2/core/address.proto
envoy/api/v2/lds.proto

Corresponding PR https://github.com/envoyproxy/envoy/pull/2922.

docs: release notes and unhide fields for IP_FREEBIND support.

---

envoy/api/v2/core/health_check.proto

This supports sending additional HTTP headers for each request
that is sent to the health checked cluster. 
Ref: https://github.com/envoyproxy/envoy/issues/2888

health check: support sending additional headers

---

docs/build.sh

The current build.sh file will attempt to use the default python version (in my case 3.6) instead of python2.7 which seems to be the required version due to the standard library having removed StringIO from python3.
Signed-off-by: Nicholas Johns <nicholas.a.johns5@gmail.com>

Build: Add explicit python version to virtualenv in /docs/build.sh

---

docs/root/configuration/listener_filters/original_dst_filter.rst
docs/root/intro/version_history.rst
envoy/api/v2/lds.proto

Signed-off-by: Romain Lenglet <romain@covalent.io>

docs: release note and unhide transparent LDS field

---

envoy/config/filter/http/transcoder/v2/transcoder.proto

the purpose of this PR is to add an option to the JSON-gRPC transcoder filter to allow preserving the original routing decision made by Envoy before this filter is called. Sometimes it is not desired that Envoy will not recalculate the route for a transcoded request; this option makes available that use case for the user.
Discussion can be found here: https://github.com/envoyproxy/envoy/issues/2847

gRPC/JSON transcoder: enable preserving route after headers modified

---

docs/root/intro/version_history.rst
envoy/api/v2/core/health_check.proto

This unhides request-headers-to-add field for HTTP health check and put a
release note line in the version history.

docs: unhide request headers to add field for health check

---

envoy/api/v2/route/route.proto

Per https://github.com/envoyproxy/envoy/issues/2851, adding metadata object to the specific routed cluster. envoy patch is ready and a PR for envoy will be created when this PR is merged (so I can update the repository_locations.bzl)

add cluster metadata to a route

---

envoy/api/v2/endpoint/endpoint.proto

This provides an alternative health check port, if set it allows an
upstream host to have different health check address port.
Ref: https://github.com/envoyproxy/envoy/issues/439

health check: add optional alternative health check port

---

docs/root/operations/admin.rst
docs/root/operations/fs_flags.rst

Signed-off-by: Joshua Marantz jmarantz@google.com
envoyproxy/envoy#2971 adds warning-checks that mutations should be POSTed. This documents that status. In a future PR, mutations will fail if they are not POSTs.
See envoyproxy/envoy#2763 for more detail.

Document that admin mutations should be POST

---

envoy/api/v2/lds.proto

Add TCP_FASTOPEN listener option
API changes for: envoyproxy/envoy#2793
Signed-off-by: Bjoern Metzdorf <bmetzdorf@apple.com>

lds: Add TCP_FASTOPEN listener option

---

docs/root/intro/version_history.rst

See also: https://github.com/envoyproxy/envoy/pull/3001
Testing:
```
ci/run_envoy_docker.sh ci/do_ci.sh bazel.docs
cd generated/docs
python -m SimpleHTTPServer $PORT
```
Then navigated a browser to http://localhost:$PORT/intro/version_history.html and made sure all the new references worked, and formatting came out OK.

Admin mutations must be issued as POST as of 1.7.

---

envoy/api/v2/route/route.proto

This reverts https://github.com/envoyproxy/data-plane-api/pull/598.
I believe the best practice to remove protos is to use reserve, so that's why I did.
This is a special case as these protos were never used; so perhaps we can remove it all together?

Remove cluster_metadata

---

envoy/api/v2/auth/cert.proto

This clarifies that `verify_certificate_hash` should be the _fingerprint_ of the cert, since "hash" is a little ambiguous and might lead to people (e.g. me) trying to hash the cert file itself.

docs: Clarify verify_certificate_hash docs

---

envoy/config/metrics/v2/stats.proto

Add prefix field to StatsdSink proto definition to support custom prefixes.
See envoyproxy/envoy#2897 for more details.
Signed-off-by: Akhil Thampy <akhil@akhilthampy.com>

stats:  add prefix to StatsConfig

---

docs/root/intro/version_history.rst
envoy/api/v2/core/health_check.proto

Three new settings are added to override health check intervals for hosts that are unhealthy or in transitioning state. This is necessary to achieve feature parity with HAProxy's [`fastinter` and `downinter`](https://www.haproxy.com/documentation/aloha/7-0/traffic-management/lb-layer7/health-checks/#health-check-parameters), thus trivializing the transition from the latter to Envoy.
Envoy PR: https://github.com/envoyproxy/envoy/pull/3048
This is the data plane side of the implementation for the issue https://github.com/envoyproxy/envoy/issues/2499.

health check: adding unhealthy interval overrides

---

envoy/config/filter/accesslog/v2/BUILD
envoy/config/filter/accesslog/v2/accesslog.proto

define an access log filter to filter requests based on the value of a specified header.
This is the initial data plane api change for the issue envoyproxy/envoy#2544.
Signed-off-by: Kevin Chan <kevintchan@yahoo.com>

access log: add header based filter

---

.github/workflows/mirror.yml
ci/mirror.sh

Currently Envoy CI uses an SSH key with all powers to sync this repo by pushing to it
This is not optimally secure, and furthermore this pattern regularly causes Envoy CI to flake racing to checkout downstream repos.
I have created an app with just wf trigger permissions and added it to this repo
This PR adds a workflow that can be triggered to sync Envoy by pulling from it

ci: Add sync workflow
