envoyproxy/data-plane-api

- api/BUILD
- api/address.proto
- api/base.proto
- api/cds.proto
- api/health_check.proto
- api/lds.proto
- api/rds.proto
- api/ssl_context.proto
The idea here is to get into the repository something with reasonable
fidelity to the early drafts that have been floated.
> Draft CDS API.

- api/BUILD
- api/eds.proto
- api/health_check.proto
The idea here is to get into the repository something with reasonable
fidelity to the early drafts that have been floated
> Draft EDS API.

- api/BUILD
- api/base.proto
- api/cds.proto
- api/eds.proto
- api/hds.proto
The idea here is to get into the repository something with reasonable
fidelity to the early drafts that have been floated.
> Draft HDS API.

- api/address.proto
- api/base.proto
- api/cds.proto
- api/eds.proto
- api/hds.proto
- api/health_check.proto
- api/lds.proto
- api/rds.proto
- api/tls_context.proto
> Package namespace versioning for v2 API.

- api/BUILD
- api/eds.proto
- bazel/api_build_system.bzl
Also bonus fix to eds.proto, it doesn't need the address.proto import.
> Add has_services annotation to api_proto_library.

- WORKSPACE
- api/cds.proto
- api/eds.proto
- api/hds.proto
- api/lds.proto
- api/rds.proto
- bazel/api_build_system.bzl
Generalizes #9 and adds googleapis fetch/build support.
> HTTP endpoints for all xDS APIs.

- api/base.proto
- api/cds.proto
- api/health_check.proto
- api/rds.proto
* Remove unused imports.
* Some _ms/Duration stragglers.
> api: trivial cleanups.

- api/rds.proto
> rds: make hash policy extensible.

- api/rds.proto
> rds: add path regex option, remove priority from VirtualCluster.

- README.md
> doc: rename Rate Limit Service to Rate Limit Discovery Service.

- api/BUILD
- api/accesslog.proto
- api/base.proto
- api/rds.proto
This commit proposes a proto definition for access logs.  It's still a rough
cut and documentation needs to be improved, please don't merge yet.  Comments
welcome.
> Add a proto definition for Access Logs.

- api/BUILD
- api/rlds.proto
@htuch Adding the ratelimit.proto file as is currently in the ratelimit repo. I am adding it under the `envoy.api.v1` package given that we are changing the name to RLDS for v2.
> RLDS: add RLDS v2 proto

- api/rds.proto
> add missing V2-API-DIFF tag

- api/rds.proto
> Make RouteConfiguration self-describing.

- api/base.proto
> api: add a notion of build version to Node identity.

- api/base.proto
> api: add notion of canary to DiscoveryResponse.

- api/cds.proto
I think this should be all of them now, the translator is now
implemented (but not validated by tests yet).
> cds: some more fixes to match v1 schema and v2 proto.

- api/health_check.proto
This is really quite HTTP specific.
> health_check: move service_name into HttpHealthCheck.

- api/BUILD
- api/bootstrap.proto
> bootstrap: remove unused import.

- api/address.proto
This is for both resolved and unresolved, so be more accurate.
> address: s/named_address/socket_address/

- api/rds.proto
Missing documentation but I first want to discuss if everything is correct.
> Add CORS settings

- README.md
lyft -> envoyproxy
docs -> ''
ads -> discovery
> Update links with a name change.

- api/eds.proto
> eds: clarify total_error_requests as HTTP 5xx.

- api/rds.proto
> rds: add comment for Metadata field in the Route message

- api/rds.proto
> rds: fix accidental commit

- api/cds.proto
Removing a comment that was made stale by https://github.com/envoyproxy/envoy/pull/1806
Signed-off-by: Jose Nino jnino@lyft.com
> cds: remove stale comment

- api/address.proto
> address: fix typo

- api/filter/network/BUILD
- api/filter/network/tcp_proxy.proto
> Add AccessLog config to tcp_proxy

- api/filter/http/BUILD
- api/filter/http/lua.proto
> add HTTP lua filter config

- api/rds.proto
Fixes missed comments in pr #217 to remove 304 and add 307 and 308.
cc: @PiotrSikora @mattklein123 
Signed-off-by: Constance Caramanolis <ccaramanolis@lyft.com>
> Remove 304 response code and add 307 and 308.

- api/lds.proto
> lds: add drain type option

- api/cds.proto
Signed-off-by: Jonathan Oddy <jonathan.oddy@transferwise.com>
> CDS: Add consecutive_gateway_failure to outlier detection

- api/filter/http/BUILD
- api/filter/http/health_check.proto
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>
> health check filter doc fix

- .circleci/config.yml
- ci/build_setup.sh
- ci/do_ci.sh
- docs/build.sh
- docs/publish.sh
> docs: push to envoy-docs/latest

- docs/root/configuration/network_filters/tcp_proxy_filter.rst
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>
> missing comma in tcp_proxy_filter.rst json

- docs/root/configuration/access_log.rst
> Document text access log fields UPSTREAM_LOCAL_ADDRESS and DOWNSTREAM_ADDRESS

- docs/root/configuration/cluster_manager/cluster_outlier_detection.rst
- docs/root/configuration/cluster_manager/cluster_runtime.rst
- docs/root/configuration/cluster_manager/cluster_stats.rst
- docs/root/intro/arch_overview/outlier.rst
Signed-off-by: Jonathan Oddy <jonathan.oddy@transferwise.com>
> Docs updates to add gateway failure outlier and deprecate old counters.

- api/filter/network/BUILD
- api/filter/network/tcp_proxy.proto
- docs/root/configuration/cluster_manager/cluster_stats.rst
> Add configuration for tcp proxy connection attempts.

- api/filter/network/BUILD
> Remove duplicate dep line which caused bazel error

- api/BUILD
- api/address.proto
- api/base.proto
- tools/protodoc/protodoc.py
> docs/constraints: address.proto and base.proto finalized.

- XDS_PROTOCOL.md
> docs: resource hint explanation improvements in XDS_PROTOCOL.md.

- api/BUILD
- api/filter/http/BUILD
- api/filter/network/BUILD
- api/filter/network/http_connection_manager.proto
- docs/build.sh
- docs/root/api-v2/filter/http/http.rst
- docs/root/configuration/http_conn_man/http_conn_man.rst
- docs/root/configuration/overview/v2_overview.rst
- tools/BUILD
- tools/generate_listeners.py
> filter: move http_connection_manager from http to network namespace.

- docs/root/configuration/overview/v2_overview.rst
- docs/root/operations/cli.rst
Companion PR to https://github.com/envoyproxy/envoy/pull/2105.
> docs: --v2-config-only CLI flag.

- api/eds.proto
- api/health_check.proto
- docs/root/api-v1/api.rst
- docs/root/api-v1/cluster_manager/cluster_hc.rst
- docs/root/api-v1/cluster_manager/cluster_manager.rst
- docs/root/configuration/cluster_manager/cluster_hc.rst
> docs: health_check.proto

- api/BUILD
- api/filter/http/lua.proto
- docs/build.sh
- docs/root/api-v1/http_filters/lua_filter.rst
- docs/root/api-v2/filter/http/http.rst
- docs/root/configuration/http_filters/lua_filter.rst
> docs: lua filter

- api/filter/fault.proto
- api/filter/http/fault.proto
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>
> fault filter validation

- api/BUILD
- api/filter/http/router.proto
- docs/build.sh
- docs/root/api-v1/http_filters/router_filter.rst
- docs/root/api-v2/filter/http/http.rst
- docs/root/configuration/http_filters/router_filter.rst
> docs: router filter

- api/cds.proto
- docs/root/configuration/cluster_manager/cluster.rst
- docs/root/configuration/cluster_manager/cluster_ring_hash_lb_config.rst
- docs/root/configuration/cluster_manager/cluster_runtime.rst
Update v1 docs based on the changes in https://github.com/envoyproxy/envoy/pull/2061
Signed-off-by: Daniel Hochman <danielhochman@users.noreply.github.com>
> Update v1 ring hash lb docs

- api/BUILD
- api/filter/http/buffer.proto
- docs/build.sh
- docs/root/api-v1/http_filters/buffer_filter.rst
- docs/root/configuration/http_filters/buffer_filter.rst
> docs: buffer filter

- api/BUILD
- api/filter/network/redis_proxy.proto
- docs/build.sh
- docs/root/api-v1/network_filters/redis_proxy_filter.rst
- docs/root/configuration/network_filters/redis_proxy_filter.rst
> docs: redis proxy

- api/bootstrap.proto
- api/sds.proto
> docs: sds.proto

- api/BUILD
- api/filter/http/fault.proto
- docs/build.sh
- docs/root/api-v1/http_filters/fault_filter.rst
- docs/root/configuration/http_filters/fault_filter.rst
> docs: fault filter

- docs/root/api-v1/cluster_manager/cluster.rst
- docs/root/api-v1/cluster_manager/cluster_circuit_breakers.rst
- docs/root/configuration/cluster_manager/cluster_circuit_breakers.rst
- docs/root/configuration/cluster_manager/cluster_manager.rst
> docs: move shared section for circuit breakers

- .clang-format
- api/eds.proto
- ci/do_ci.sh
- tools/check_format.py
Part of implementing priorities, issue #1929 
See TODO in #2088
> Adding priority to lb stats, making all priorities uint32

- api/bootstrap.proto
- api/eds.proto
- api/filter/accesslog/accesslog.proto
- docs/root/api-v1/access_log.rst
- docs/root/api-v1/api.rst
- docs/root/configuration/access_log.rst
- docs/root/configuration/http_conn_man/headers.rst
- docs/root/intro/version_history.rst
> docs: access log and misc fixes

- docs/root/configuration/http_conn_man/headers.rst
- docs/root/configuration/http_conn_man/stats.rst
- docs/root/configuration/network_filters/mongo_proxy_filter.rst
- docs/root/configuration/runtime.rst
- docs/root/intro/arch_overview/load_balancing.rst
- docs/root/intro/arch_overview/mongo.rst
- docs/root/intro/version_history.rst
- docs/root/operations/admin.rst
> docs: 1.5.0 release notes

- api/bootstrap.proto
> bootstrap: relax some constraints as they aren't required in v2.

- api/BUILD
- api/filter/network/client_ssl_auth.proto
- docs/build.sh
- docs/root/api-v1/network_filters/client_ssl_auth_filter.rst
- docs/root/configuration/network_filters/client_ssl_auth_filter.rst
- docs/root/intro/version_history.rst
> docs: client ssl auth filter

- docs/root/api-v1/http_filters/dynamodb_filter.rst
- docs/root/api-v1/http_filters/grpc_http1_bridge_filter.rst
- docs/root/api-v1/http_filters/grpc_web_filter.rst
- docs/root/api-v1/network_filters/echo_filter.rst
- docs/root/configuration/http_filters/dynamodb_filter.rst
- docs/root/configuration/http_filters/grpc_http1_bridge_filter.rst
- docs/root/configuration/http_filters/grpc_json_transcoder_filter.rst
- docs/root/configuration/http_filters/grpc_web_filter.rst
- docs/root/configuration/network_filters/echo_filter.rst
> docs: misc empty filters

- CONTRIBUTING.md
> contrib: update docs guide

- docs/root/intro/version_history.rst
> release notes: added cluster not found option

- docs/root/about_docs.rst
- docs/root/api-v1/api.rst
> docs: update about docs page

- docs/root/api-v2/api.rst
- docs/root/api-v2/filter/filter.rst
- docs/root/api-v2/filter/http/http.rst
- docs/root/api-v2/filter/network/network.rst
> docs: remove WIP warnings

- api/filter/network/tcp_proxy.proto
> docs: tcp proxy fixes

- docs/root/configuration/http_conn_man/headers.rst
Corresponds to a change in envoyproxy/envoy#2174.
> docs: note availability of dynamic response headers

- api/filter/network/tcp_proxy.proto
> Add configuration for tcp proxy idle timeout.

- api/filter/http/gzip.proto
This PR contains the API for the gzip http filter in support of envoyproxy/envoy issue https://github.com/envoyproxy/envoy/issues/269
> filter: pb definition for gzip filter

- api/filter/accesslog/accesslog.proto
> access log: gRPC service config updates

- api/address.proto
- api/base.proto
- api/bootstrap.proto
- api/cds.proto
- api/filter/accesslog/accesslog.proto
- api/filter/fault.proto
- api/filter/network/http_connection_manager.proto
- api/rds.proto
- bazel/api_build_system.bzl
- bazel/repositories.bzl
gogo allows customizing go code generation to ensure correct-by-construction semantics.
Added a few annotations to make use of the "nullable" and "stdduration" features.
> Add gogoproto annotations

- api/BUILD
- api/bootstrap.proto
- api/stats.proto
- api/trace.proto
- docs/build.sh
- docs/root/api-v2/api.rst
This is a follow-up PR for https://github.com/envoyproxy/data-plane-api/pull/325#discussion_r154974914.
Envoy side PR: https://github.com/envoyproxy/envoy/pull/2202.
*Review Note*:
I'm not a fluent English speaker.
> api: extract tracing protos from bootstrap

- api/lds.proto
> network filters: update list of v2 supported network filters

- api/rds.proto
- docs/root/api-v1/route_config/route.rst
This diff contains the API and documentation changes in support of envoyproxy/envoy issue 2120
> Add URL query arg matching to the route configuration schema.

- api/BUILD
- api/filter/http/BUILD
- api/filter/http/squash.proto
- api/filter/network/http_connection_manager.proto
- docs/build.sh
- docs/root/api-v1/http_filters/squash_filter.rst
- docs/root/configuration/http_filters/http_filters.rst
- docs/root/configuration/http_filters/squash_filter.rst
- test/validate/BUILD
- test/validate/pgv_test.cc
This PR contains the API for the squash filter in support of squash integration in service mesh use cases.
A PR for a squash filter in envoy will follow up.
> filter: pb definition for squash filter

- docs/root/install/sandboxes/zipkin_tracing.rst
Zipkin is running on localhost
> fix IP address in example docs

- docs/root/operations/cli.rst
For https://github.com/envoyproxy/envoy/issues/1975.
> stats: docs for new --stat-tag cli arg

- docs/root/operations/admin.rst
Description: Doc changes based on https://github.com/envoyproxy/envoy/pull/2261
Note: I reviewed the contribution guidelines and might have missed something applicable here.  Please let me know.  I did run all the tests & will looked at the generated doc.
Signed-off-by: Joshua Marantz <jmarantz@google.com>
> Add doc update to reflect HTML home page being added in PR 2261

- api/auth/BUILD
- api/auth/external_auth.proto
Signed-off-by: Reuven Lazarus <rzl@google.com>
> cleanup: Add a missing has_services and remove an unused import.

- XDS_PROTOCOL.md
This change came from a conversation in the #control-plane-dev Slack channel. 
Details at: https://envoyproxy.slack.com/archives/C7LDJTM6Z/p1514113660000041
> xDS: add clarification about new requests superseding old ones

- api/base.proto
> fix config source comment

- api/base.proto
> api config source: add note about EDS backing clusters

- CONTRIBUTING.md
- ci/do_ci.sh
> Document the included check_format script

- api/auth/external_auth.proto
Clarify the spec for AttributeContext to be more accurate and easy to understand.
@mandarjog @mattklein123
> Improve documentation to the AttributeContext

- api/metrics_service.proto
Added constraint valiations
Signed-off-by: Rama <ramaraochavali@gmail.com>
> added constraint validations

- CONTRIBUTING.md
Included files that should be edited  in order to generate the RSTs and DOCs when a new .proto is added to the project.
> contributing: edited contributing file

- api/filter/accesslog/BUILD
- api/filter/accesslog/accesslog.proto
> access log: fix to use GrpcCluster

- api/auth.proto
per issue #368 
Signed-off-by: Mandar U Jog <mjog@google.com>
> Pluralize repeated field 'rule'

- STYLE.md
> style clarifications

- BUILD
Signed-off-by: Kyle Myerson <kmyerson@google.com>
> Add license declaration in BUILD.

- STYLE.md
Signed-off-by: Hong Zhang <wora2000@gmail.com>
> Add a section to explain recommended default enum value.

- docs/build.sh
- tools/protodoc/protodoc.py
Some low hanging fruit optimizations. This takes address.proto.rst build
from ~21s to ~1.7s.
> protodoc: make protodoc fast again.

- api/bootstrap.proto
- api/cds.proto
- api/filter/network/http_connection_manager.proto
- api/lds.proto
- api/sds.proto
- api/trace.proto
- docs/root/configuration/http_filters/lua_filter.rst
> docs: misc fixes

- api/config_source.proto
- docs/root/configuration/runtime.rst
Fix for https://github.com/envoyproxy/envoy/issues/2241
> docs: clarify config file watch semantics

- api/rds.proto
API changes for envoyproxy/envoy#2253.
> rds: introduce total_weight for WeightedCluster

- STYLE.md
- envoy/api/v2/README.md
- envoy/api/v2/filter/README.md
- envoy/config/README.md
- envoy/service/README.md
> style: recent lessons learned on package namespace moves.

- envoy/api/v2/filter/network/tcp_proxy.proto
> tcp proxy: add warning for deprecated_v1 field

- API_OVERVIEW.md
These were all 404ing, so this PR updates the links to point to the right file.
> Fix links in API_OVERVIEW.md

- test/validate/BUILD
- test/validate/pgv_test.cc
While there, sort includes to match BUILD file.
> build: add missing dependencies.

- docs/root/configuration/http_filters/cors_filter.rst
- docs/root/configuration/http_filters/grpc_json_transcoder_filter.rst
- docs/root/configuration/http_filters/grpc_web_filter.rst
- docs/root/configuration/http_filters/http_filters.rst
- docs/root/configuration/http_filters/lua_filter.rst
Also clarify add() behavior.
Also sort HTTP filters and normalize names.
> docs: lua replace() function

- docs/root/api-v2/api.rst
- docs/root/api-v2/bootstrap/bootstrap.rst
- docs/root/api-v2/clusters/clusters.rst
- docs/root/api-v2/common_messages/common_messages.rst
- docs/root/api-v2/http_routes/http_routes.rst
- docs/root/api-v2/listeners/listeners.rst
- envoy/api/v2/core/address.proto
- envoy/api/v2/lds.proto
- envoy/api/v2/listener/listener.proto
- envoy/api/v2/rds.proto
- envoy/api/v2/route/route.proto
- envoy/config/bootstrap/v2/bootstrap.proto
- envoy/config/filter/accesslog/v2/accesslog.proto
- envoy/config/metrics/v2/metrics_service.proto
- envoy/config/ratelimit/v2/rls.proto
I went through and reorganized things to make the v2 docs more
human browsable. I also did a few misc cleanups. There is a lot
more to do here which I'm hoping to find a contractor to pay to
work on, but this is a step in the right direction.
> docs: reorganize for readability

- docs/root/configuration/http_conn_man/headers.rst
Per the discussion in #459, the XFF documentation doesn't match the implementation. This PR modifies the docs to try to describe more clearly the interaction between `use_remote_address` and `X-Forwarded-For`.
> docs: clarify the x-forwarded-for documentation

- docs/root/faq/lb_panic_threshold.rst
- docs/root/faq/overview.rst
> faq: panic threshold

- docs/root/api-v1/network_filters/http_conn_man.rst
- envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>
> docs: unhiding 100-Continue config

- STYLE.md
- docs/root/intro/arch_overview/load_balancing.rst
- envoy/api/v2/cds.proto
Also setup a message that we can use for other missing settings such as
zone aware LB settings.
> cds: add configuration for healthy_panic_threshold

- docs/root/configuration/overview/v2_overview.rst
> docs: update broken links

- CONTRIBUTING.md
Signed-off-by: Constance Caramanolis <ccaramanolis@lyft.com>
> Update docs build links

- docs/root/intro/arch_overview/redis.rst
See https://github.com/envoyproxy/envoy/pull/2569
Signed-off-by: Daniel Hochman <danielhochman@users.noreply.github.com>
> redis: list new geo commands

- envoy/api/v2/cds.proto
Fixes the issue https://github.com/envoyproxy/data-plane-api/issues/427. Once this is approved, will follow-up with envoy changes
> Add alt_stat_name to cluster

- envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
> hcm: fix merge snafu with conflicting field numbers.

- docs/root/intro/arch_overview/load_balancing.rst
- envoy/api/v2/cds.proto
> cds: add Maglev load balancer

- envoy/api/v2/core/health_check.proto
> Enable setting host header value for HTTP HC

- docs/root/configuration/http_filters/router_filter.rst
- envoy/api/v2/cds.proto
Updated the docs as per the discussion at https://github.com/envoyproxy/data-plane-api/pull/484
> update alt_stat_name docs with cross references

- envoy/api/v2/core/health_check.proto
Signed-off-by: Alexey Baranov <me@kotiki.cc>
> Make gRPC-healthcheck options visible

- bazel/api_build_system.bzl
- envoy/api/v2/discovery.proto
Fixes issue https://github.com/envoyproxy/data-plane-api/issues/396. Once this is approved, will make Envoy side changes.
> Status support in DiscoveryRequest

- envoy/api/v2/route/route.proto
*Title:* add support for prefix_rewrite and strip_query under RedirectAction
this patch adds support for dynamically generating redirect msg based on
a request received by modifying the matched prefix or path.
ref: envoyproxy/envoy#2343
Signed-off-by: Madhavan Balasubramanian <bmadhavan@ebay.com>
> Add support for prefix_rewrite and strip_query under RedirectAction

- XDS_PROTOCOL.md
- envoy/api/v2/discovery.proto
> Remove hide-implementation and update xds protocol doc

- bazel/repositories.bzl
Signed-off-by: John Millikin <jmillikin@stripe.com>
> Switch to Skylark git_repository, which uses native Git.

- envoy/type/range.proto
> Add new go package for type

- envoy/api/v2/cds.proto
- envoy/api/v2/core/protocol.proto
Api changes for https://github.com/envoyproxy/envoy/issues/2324
> add support for idle timeout for upstream connections

- docs/root/start/sandboxes/jaeger_tracing.rst
Signed-off-by: Gary Brown <gary@brownuk.com>
> Update Jaeger links

- envoy/api/v2/route/route.proto
Signed-off-by: Madhavan Balasubramanian <bmadhavan@ebay.com>
Issue ref: envoyproxy/envoy#2343
envoy ref: envoyproxy/envoy#2661
DP ref: envoyproxy/data-plane-api#456
> docs: Unhide RedirectAction.prefix_rewrite and strip_query

- docs/root/operations/admin.rst
Fixes https://github.com/envoyproxy/envoy/issues/2769
References https://github.com/envoyproxy/envoy/issues/2763
> admin: add security warning

- docs/root/configuration/http_conn_man/headers.rst
> docs: fix broken link in HTTP header doc

- envoy/api/v2/core/protocol.proto
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>
> unhiding http1.0 config

- docs/root/configuration/overview/v1_overview.rst
> v1 api: link to deprecation schedule

- docs/root/api-v1/cluster_manager/cluster_hc.rst
- envoy/api/v2/core/health_check.proto
This to help to fix: https://github.com/envoyproxy/envoy/issues/2782 I'll prepare the corresponding changeset to envoy.
> Add no traffic interval config

- docs/root/intro/version_history.rst
- envoy/api/v2/core/protocol.proto
Doc Changes for https://github.com/envoyproxy/envoy/pull/2714
> doc changes for idle timeout

- docs/root/configuration/http_conn_man/headers.rst
- docs/root/intro/arch_overview/tracing.rst
- docs/root/intro/version_history.rst
Documentation to accompany https://github.com/envoyproxy/envoy/pull/2764.
Signed-off-by: Gary Brown <gary@brownuk.com>
> Update description of B3 header usage

- docs/root/configuration/cluster_manager/cluster_runtime.rst
- docs/root/intro/arch_overview/load_balancing.rst
removed here: https://github.com/envoyproxy/envoy/pull/2061/files#diff-acc2db8f613545cd2c5d6ad20a26f193L95
> docs: remove runtime ring hash ref

- docs/root/configuration/cluster_manager/cluster_stats.rst
> added idle timeout stat

- docs/root/configuration/http_filters/router_filter.rst
- docs/root/configuration/http_filters/squash_filter.rst
- docs/root/intro/version_history.rst
- docs/root/operations/admin.rst
- envoy/api/v2/cds.proto
- envoy/api/v2/core/address.proto
- envoy/api/v2/route/route.proto
This is the merge of the raw release notes prior to implementing the
new procedure.
> docs: 1.6.0 release notes

- docs/root/configuration/http_filters/lua_filter.rst
- docs/root/intro/version_history.rst
Recreate https://github.com/envoyproxy/data-plane-api/pull/535 with merge conflict fixed.
cc @dio
> docs: lua metadata API

- docs/root/intro/arch_overview/load_balancing.rst
- envoy/api/v2/cds.proto
- envoy/api/v2/endpoint/endpoint.proto
Introduce the concept of locality weighted LB (as distinct from zone
aware LB) in the docs and a new field in Cluster, locality_weighted_lb,
for configuring this behavior.
> lb: locality weighted LB.

- docs/root/intro/version_history.rst
- docs/root/operations/admin.rst
Added ref to run-time logging levels after removing NVLOG.
> logger: added ref to run-time logging levels after removing NVLOG.

- docs/root/intro/version_history.rst
Release note for https://github.com/envoyproxy/envoy/pull/2787
Signed-off-by: Gary Brown <gary@brownuk.com>
> Release note related to envoy #2787

- envoy/config/filter/http/health_check/v2/BUILD
Signed-off-by: John Millikin <jmillikin@stripe.com>
> Add `api_go_proto_library` target for HealthCheck proto.

- docs/root/intro/version_history.rst
- docs/root/operations/cli.rst
This PR accompanies: https://github.com/envoyproxy/envoy/pull/2878
> Add documentation for the --config-yaml flag.

- docs/root/start/start.rst
See: https://github.com/envoyproxy/envoy/pull/2850
Signed-off-by: Nicholas Johns <nicholas.a.johns5@gmail.com>
> Docs: quickstart guide to use publish docker images

- .circleci/config.yml
- ci/do_ci.sh
> ci: remove docs/format jobs.
